
director-test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH != "demo"  
      changes:
        - services/director/packages.txt
        - services/director/server.txt
  script:
    - echo "Testing the app2"


director-test-demo:
  stage: test-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo"  
      changes: 
        - services/director/packages.txt
        - services/director/server.txt
  script:
    - echo "Testing the app2 demo"


director-build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH != "demo" 
      changes:
        - services/director/packages.txt
        - services/director/server.txt
  needs: ["director-test"]
  script:
    - echo "Building the app2"

director-build-demo:
  stage: build-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - services/director/packages.txt
        - services/director/server.txt
  needs: ["director-test-demo"]
  script:
    - echo "Building the app2 for demo"

director-deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH != "demo" 
      changes:
        - services/director/packages.txt
        - services/director/server.txt
  needs: ["director-build"]
  script:
    - echo "Deploying the app2"

director-deploy-demo:
  stage: deploy-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - services/director/packages.txt
        - services/director/server.txt
  needs: ["director-build-demo"]
  script:
    - echo "Deploying the app2"