image: node:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Testing the app"

build:
  stage: build
  needs: ["test"]
  script:
    - echo "Building the app"

deploy:
  stage: deploy
  needs: ["build"]
  script:
    - echo "Deploying the app"