# publish:
#   stage: build
#   image: 
#     name: docker:latest
#   services:
#     - docker:19-dind
#   before_script:
#     - apk add --no-cache curl jq python3 py3-pip
#     - pip install awscli
#     - aws configure set aws_access_key_id AKIA54RGBLJCQ3MJ2SV6
#     - aws configure set aws_secret_access_key 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
#     - aws configure set default.region eu-west-1
#     - aws ecr get-login-password | docker login --username AWS --password-stdin 954636261957.dkr.ecr.eu-west-1.amazonaws.com/sibros
#     - LAST_IMAGE_TAG=$(aws ecr describe-images --repository-name sibros --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]')
#     - echo $LAST_IMAGE_TAG
#     - MANIFEST=$(aws ecr batch-get-image --repository-name sibros --image-ids imageTag=$LAST_IMAGE_TAG --output json | jq --raw-output --join-output '.images[0].imageManifest')
#     - echo $MANIFEST
#     - aws ecr put-image --repository-name sibros --image-tag rollback --image-manifest "$MANIFEST" 
#     - aws --version
#     - docker info
#     - docker --version
#   script:
#     - docker build -t 954636261957.dkr.ecr.eu-west-1.amazonaws.com/sibros:$CI_COMMIT_SHORT_SHA .
#     - docker push 954636261957.dkr.ecr.eu-west-1.amazonaws.com/sibros:$CI_COMMIT_SHORT_SHA


EKS:
  stage: deploy
  script:
    - apt update -y
    - apt install -y curl python3-pip
    - pip3 install awscli typing
    - pip3 install --upgrade botocore==1.21.57
    - export AWS_ACCESS_KEY_ID=AKIA54RGBLJCQ3MJ2SV6
    - export AWS_SECRET_ACCESS_KEY=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
    - export AWS_DEFAULT_REGION=eu-west-1
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - aws sts get-caller-identity
    - aws eks --region eu-west-1 update-kubeconfig --name CofeApp
    - kubectl set image deployment/sibros sibros=954636261957.dkr.ecr.eu-west-1.amazonaws.com/sibros:latest