image: node:latest

stages:
  - test
  - build
  - deploy

# Job's name
test:
  # Define stage
  stage: test
  # What to run on the job.
  script:
    - echo "Testing the app"

build:
  stage: run
  script:
    - echo "Building the app"

deploy:
  stage: run
  script:
    - echo "Deploying the app"