
ms1-test:
  stage: test
  rules:
    - changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  script:
    - echo "Testing the app1"


ms1-test-demo:
  stage: test-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - microservice1/packages.txt
        - microservice1/server.txt
  script:
    - echo "Testing the app1 demo"


ms1-build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH != "demo" 
      changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  script:
    - echo "Building the app1"

ms1-build-demo:
  stage: build-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - microservice1/packages.txt
        - microservice1/server.txt
  needs: ["ms1-test-demo"]
  script:
    - echo "Building the app1 for demo"

ms1-deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH != "demo" 
      changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  needs: ["ms1-build"]
  script:
    - echo "Deploying the app1"

ms1-deploy-demo:
  stage: deploy-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - microservice1/packages.txt
        - microservice1/server.txt
  script:
    - echo "Deploying the app1"