
ms1-test:
  stage: test
  rules:
    - changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  script:
    - echo "Testing the app1"

ms1-build:
  stage: build
  rules:
    - changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  needs: ["ms1-test"]
  script:
    - echo "Building the app1"

ms1-build-demo:
  stage: build-demo
  only:
    - if: $CI_COMMIT_BRANCH == 'demo'
  rules:
    - changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  needs: ["ms1-test"]
  script:
    - echo "Building the app1 for demo"

ms1-deploy:
  stage: deploy
  rules:
    - changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  needs: ["ms1-build"]
  script:
    - echo "Deploying the app1"

ms1-deploy-demo:
  only:
    - if: $CI_COMMIT_BRANCH == 'demo'
  rules:
    - changes:
        - microservice1/packages.txt
        - microservice1/server.txt
  needs: ["ms1-build"]
  script:
    - echo "Deploying the app1"