
atlas-test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH != "demo"  
      changes:
        - services/atlas/packages.txt
        - services/atlas/server.txt
  # environment:
  #   name: dev
  script:
    - echo "Testing the app1"


atlas-test-demo:
  stage: test-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo"  
      changes: 
        - services/atlas/packages.txt
        - services/atlas/server.txt
  # environment:
  #   name: demo
  script:
    - echo "Testing the app1 demo"


atlas-build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH != "demo" 
      changes:
        - services/atlas/packages.txt
        - services/atlas/server.txt
  needs: ["atlas-test"]
  # environment:
  #   name: dev
  script:
    - echo "Building the app1"

atlas-build-demo:
  stage: build-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - services/atlas/packages.txt
        - services/atlas/server.txt
  needs: ["atlas-test-demo"]
  # environment:
  #   name: demo
  script:
    - echo "Building the app1 for demo"

atlas-deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH != "demo" 
      changes:
        - services/atlas/packages.txt
        - services/atlas/server.txt
  needs: ["atlas-build"]
  # environment:
  #   name: dev
  script:
    - echo "Deploying the app1"

atlas-deploy-demo:
  stage: deploy-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "demo" 
      when: always 
      changes: 
        - services/atlas/packages.txt
        - services/atlas/server.txt
  needs: ["atlas-build-demo"]
  # environment:
  #   name: demo
  script:
    - echo "Deploying the app1"