name: Zip and Upload to S3

on:
  push:
    branches:
      - master  # Adjust as needed

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip and upload to S3
        uses: NotCoffee418/s3-zip-upload@v1.4
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_MODE: ZIP
          SOURCE_PATH: .                  # zips the whole repo (excluding .git by default)
          DEST_FILE: source-${{ github.sha }}.zip
