name: Zip and Upload to S3

on:
  push:
    branches:
      - master  # Adjust as needed

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::390402557022:role/S3GithubRole
          role-session-name: samplerolesession
          aws-region: me-central-1

      - name: Zip repository
        run: |
          # Exclude the .git history to keep the zip clean
          zip -r source_code.zip . -x "*.git*"

      - name: Upload zip to S3
        run: |
          aws s3 cp source_code.zip s3://testcoderepo801/source_code.zip
