name: Zip and Upload to S3

on:
  push:
    branches:
      - master  # Adjust as needed
permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::390402557022:role/S3GithubRole
          role-session-name: samplerolesession
          aws-region: me-central-1
      # Upload a file to AWS s3
      - name: Copy index.html to s3
        run: |
          aws s3 cp ./index.js s3://testcoderepo801/
