
ms2-test:
  stage: test
  rules:
    - changes:
        - microservice2/packages.txt
        - microservice2/server.txt
  script:
    - echo "Testing the app2"

ms2-build:
  stage: build
  rules:
    - changes:
        - microservice2/packages.txt
        - microservice2/server.txt
  needs: ["ms2-test"]
  script:
    - echo "Building the app2"

ms2-deploy:
  stage: deploy
  rules:
    - changes:
        - microservice2/packages.txt
        - microservice2/server.txt
  needs: ["ms2-build"]
  script:
    - echo "Deploying the app2"